export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const PROMOS_LOADING = 'PROMOS_LOADING';
export const ADD_PROMOS = 'ADD_PROMOS';
export const PROMOS_FAILED = 'PROMOS_FAILED';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const FAVORITES_LOADING = 'FAVORITES_LOADING';
export const FAVORITES_FAILED = 'FAVORITES_FAILED';
export const ADD_FAVORITES = 'ADD_FAVORITES';

export const ADD_DEVELOPERS = 'ADD_DEVELOPERS';
export const DEVELOPERS_LOADING = 'DEVELOPERS_LOADING';
export const DEVELOPERS_FAILED = 'DEVELOPERS_FAILED';

export const COURSES_LOADING = 'COURSES_LOADING';
export const COURSES_FAILED = 'COURSES_FAILED';
export const ADD_COURSES = 'ADD_COURSES';
export const ADD_COURSEITEMS = 'ADD_COURSEITEMS';
export const COURSEITEMS_LOADING = 'COURSEITEMS_LOADING';
export const COURSEITEMS_FAILED = 'COURSEITEMS_FAILED';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const USERINFOS_LOADING = 'USERINFOS_LOADING';
export const USERINFOS_FAILED = 'USERINFOS_FAILED';
export const ADD_USERINFOS = 'ADD_USERINFOS';
